{% set version = "8.4" %}

package:
  name: primecount
  version: "{{ version }}"

source:
  url: https://github.com/kimwalisch/primecount/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c7bf47c041bfe4c3912a0d503ea44c1bb6c9003427c12574a6b497748b387612
  patches:
    - fix-to_chars-macos.patch  # [osx]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('primecount', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make         # [unix]
    - ninja        # [win]
    - libgomp      # [linux]
    - llvm-openmp  # [osx or win]
    - clang        # [win]
  host:
    - primesieve

test:
  commands:
    # Check libraries exist
    - test -f "${PREFIX}/include/primecount.h"  # [unix]
    - test -f "${PREFIX}/lib/libprimecount${SHLIB_EXT}"  # [unix]
    - if not exist %PREFIX%\\Library\\include\\primecount.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\primecount.lib exit 1  # [win]

    # Test CLIs.
    - primecount 1e5

about:
  home: https://github.com/kimwalisch/primecount
  license: BSD-2-Clause
  license_file: COPYING
  summary: Fast prime counting function implementations

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
